import { readFileSync } from 'node:fs';
import { join } from 'node:path';

// Directory where per-host restic coverage JSON is mounted (read-only).
// Each file is `<host>.json`, the raw output of `restic snapshots --latest 1 --json`.
const COVERAGE_DIR = process.env.COVERAGE_DIR ?? '/coverage';

interface Snapshot {
  time: string;
  paths: string[];
  hostname: string;
  program_version?: string;
}

function loadSnapshot(host: string): Snapshot | null {
  try {
    const raw = readFileSync(join(COVERAGE_DIR, `${host}.json`), 'utf-8');
    const arr = JSON.parse(raw) as Snapshot[];
    return Array.isArray(arr) && arr.length > 0 ? arr[arr.length - 1] : null;
  } catch {
    return null;
  }
}

/**
 * Renders the paths covered by the latest restic snapshot for a host,
 * read at build time from the mounted coverage file. Generated by restic
 * itself — this cannot drift from what is actually backed up.
 *
 * Usage in MDX:  <BackupCoverage host="optiplex" />
 */
export function BackupCoverage({ host }: { host: string }) {
  const snap = loadSnapshot(host);

  if (!snap) {
    return (
      <div className="my-4 rounded-lg border border-fd-border bg-fd-muted/50 p-4 text-sm text-fd-muted-foreground">
        No coverage data for <code>{host}</code> — the backup job has not yet
        written <code>{host}.json</code>, or the coverage mount is missing.
      </div>
    );
  }

  const when = new Date(snap.time);
  const whenStr = isNaN(when.getTime())
    ? snap.time
    : when.toISOString().slice(0, 16).replace('T', ' ') + ' UTC';

  return (
    <div className="my-4">
      <p className="text-sm text-fd-muted-foreground mb-2">
        Live from the latest snapshot ({snap.paths.length} paths, backed up{' '}
        {whenStr}
        {snap.program_version ? `, ${snap.program_version}` : ''}). Generated by
        restic — cannot drift.
      </p>
      <ul className="text-sm">
        {snap.paths.map((p) => (
          <li key={p}>
            <code>{p}</code>
          </li>
        ))}
      </ul>
    </div>
  );
}
